name: dwel_lbox
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:


  cupertino_icons: ^1.0.0
  font_awesome_flutter: 8.8.1
  shared_preferences: ^0.5.8
  #  firebase_messaging: 6.0.16
  back_button_interceptor: ^4.3.1
  swipedetector: ^1.2.0
  localstorage: 3.0.2+5
  notification_permissions: 0.4.4
  flutter_webview_plugin: ^0.3.11
  flutter_speed_dial: ^1.2.5
  unicorndial: ^1.1.5
  flare_splash_screen: 3.0.1
  firebase_core: 0.4.4 # keep these version as there is new issue# with the latest firebase https://github.com/FirebaseExtended/flutterfire/issues/2084
  #  onesignal_flutter: 2.4.1
  custom_splash: ^0.0.2
  after_layout: 1.0.7+2
  url_launcher: ^5.4.10
  connectivity: ^0.4.9

  provider: ^4.1.3+1
  flutter_inappwebview: ^3.2.0
  flutter_spinkit: ^4.1.2+1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter

#  flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets\images\dwellboxlogo.png
  color: "ffffff"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

